// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	CompilationAPIService := openapi.NewCompilationAPIService()
	CompilationAPIController := openapi.NewCompilationAPIController(CompilationAPIService)

	StatusAPIService := openapi.NewStatusAPIService()
	StatusAPIController := openapi.NewStatusAPIController(StatusAPIService)

	router := openapi.NewRouter(CompilationAPIController, StatusAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
