basePath: /v1
definitions:
  handler.AliveResponse:
    description: AliveResponse represents a response for the alive endpoint
    properties:
      message:
        example: OK
        type: string
    type: object
  handler.ArtifactResponse:
    description: ArtifactResponse represents a response for a compilation artifacts
      request
    properties:
      bin:
        example: YmluYXJ5IGRhdGE=
        type: string
      elf:
        example: ZWxmIGRhdGE=
        type: string
      hex:
        example: aGV4IGRhdGE=
        type: string
      name:
        example: test
        type: string
    type: object
  handler.Compilation:
    description: Compilation represents a compilation request
    properties:
      fqbn:
        example: arduino:avr:uno
        type: string
      ota:
        example: false
        type: boolean
      sketch:
        allOf:
        - $ref: '#/definitions/handler.Sketch'
        description: "Path\tstring `json:\"path\"`"
      verbose:
        example: false
        type: boolean
    type: object
  handler.CompilationResponse:
    description: CompilationResponse represents a response for a compilation request
    properties:
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      status:
        example: created
        type: string
    type: object
  handler.ErrBadRequestResponse:
    description: ErrBadRequestResponse represents a bad request response
    properties:
      err:
        example: bad request
        type: string
    type: object
  handler.ErrForbiddenResponse:
    description: ErrForbiddenResponse represents a forbidden response
    properties:
      err:
        example: forbidden
        type: string
    type: object
  handler.ErrGoneResponse:
    description: ErrGoneResponse represents a gone response
    properties:
      err:
        example: gone
        type: string
    type: object
  handler.ErrInternalServerErrorResponse:
    description: ErrInternalServerErrorResponse represents an internal server error
      response
    properties:
      err:
        example: internal server error
        type: string
    type: object
  handler.ErrMethodNotAllowedResponse:
    description: ErrMethodNotAllowedResponse represents a method not allowed response
    properties:
      err:
        example: method not allowed
        type: string
    type: object
  handler.ErrNotFoundResponse:
    description: ErrNotFoundResponse represents a not found response
    properties:
      err:
        example: not found
        type: string
    type: object
  handler.ErrRateLimitExceededResponse:
    description: ErrRateLimitExceededResponse represents a rate limit exceeded response
    properties:
      err:
        example: rate limit exceeded
        type: string
    type: object
  handler.ErrServiceUnavailableResponse:
    description: ErrServiceUnavailableResponse represents a service unavailable response
    properties:
      err:
        example: service unavailable
        type: string
    type: object
  handler.ErrUnauthorizedResponse:
    description: ErrUnauthorizedResponse represents an unauthorized response
    properties:
      err:
        example: unauthorized
        type: string
    type: object
  handler.File:
    description: File represents a file to be compiled
    properties:
      data:
        example: |-
          #include <Arduino.h>
          void setup() {}
          void loop() {}
        type: string
      name:
        example: test.ino
        type: string
    type: object
  handler.IncludedLibraries:
    description: IncludedLibraries represents the libraries to be included in the
      compilation
    properties:
      included_libs:
        items:
          $ref: '#/definitions/handler.Library'
        type: array
    type: object
  handler.Library:
    description: Library represents a library to be included in the compilation
    properties:
      name:
        example: ArduinoJson
        type: string
      version:
        example: 6.17.2
        type: string
    type: object
  handler.LogsResponse:
    description: LogsResponse represents a response for a compilation logs request
    properties:
      stderr:
        example: 'Error: World not found'
        type: string
      stdout:
        example: Hello, World!
        type: string
    type: object
  handler.Sketch:
    description: Sketch represents a sketch to be compiled
    properties:
      files:
        items:
          $ref: '#/definitions/handler.File'
        type: array
      ino:
        $ref: '#/definitions/handler.File'
      metadata:
        $ref: '#/definitions/handler.IncludedLibraries'
      name:
        example: test
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the documentation for the Builder API service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Builder API Documentation
  version: "2.0"
paths:
  /alive:
    get:
      description: Get the status of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.AliveResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrBadRequestResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/handler.ErrMethodNotAllowedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrInternalServerErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handler.ErrServiceUnavailableResponse'
      summary: Get the status of the server
      tags:
      - status
  /compilations:
    post:
      consumes:
      - application/json
      description: Add a new compilation to the queue
      parameters:
      - description: Compilation object that needs to be added to the queue
        in: body
        name: value
        required: true
        schema:
          $ref: '#/definitions/handler.Compilation'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CompilationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrUnauthorizedResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.ErrForbiddenResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/handler.ErrMethodNotAllowedResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/handler.ErrRateLimitExceededResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrInternalServerErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handler.ErrServiceUnavailableResponse'
      summary: Add a new compilation
      tags:
      - compilation
  /compilations/{id}:
    get:
      description: Get the status of a compilation
      parameters:
      - description: Compilation object we want to know the status of
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CompilationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrUnauthorizedResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.ErrForbiddenResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrNotFoundResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/handler.ErrMethodNotAllowedResponse'
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/handler.ErrGoneResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/handler.ErrRateLimitExceededResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrInternalServerErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handler.ErrServiceUnavailableResponse'
      summary: Get the status of a compilation
      tags:
      - compilation
  /compilations/{id}/artifacts:
    get:
      description: Get the compilation artifacts
      parameters:
      - description: Compilation object we want to retrieve the artifacts of
        in: path
        name: id
        required: true
        type: string
      - description: 'Type of artifact we want to retrieve: bin, elf, hex'
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ArtifactResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrUnauthorizedResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.ErrForbiddenResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrNotFoundResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/handler.ErrMethodNotAllowedResponse'
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/handler.ErrGoneResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/handler.ErrRateLimitExceededResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrInternalServerErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handler.ErrServiceUnavailableResponse'
      summary: Get the compilation arfitacts
      tags:
      - compilation
  /compilations/{id}/cancel:
    post:
      description: Stop a compilation in the queue
      parameters:
      - description: Compilation object that needs to be stopped
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CompilationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrUnauthorizedResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.ErrForbiddenResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrNotFoundResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/handler.ErrMethodNotAllowedResponse'
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/handler.ErrGoneResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/handler.ErrRateLimitExceededResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrInternalServerErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handler.ErrServiceUnavailableResponse'
      summary: Stop a compilation
      tags:
      - compilation
  /compilations/{id}/logs:
    get:
      description: Get the compilation logs
      parameters:
      - description: Compilation object we want to retrieve the logs of
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LogsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrUnauthorizedResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.ErrForbiddenResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrNotFoundResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/handler.ErrMethodNotAllowedResponse'
        "410":
          description: Gone
          schema:
            $ref: '#/definitions/handler.ErrGoneResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/handler.ErrRateLimitExceededResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrInternalServerErrorResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/handler.ErrServiceUnavailableResponse'
      summary: Get the compilation logs
      tags:
      - compilation
swagger: "2.0"
