// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi

import (
	"context"
	"net/http"
)



// CompilationAPIRouter defines the required methods for binding the api requests to a responses for the CompilationAPI
// The CompilationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a CompilationAPIServicer to perform the required actions, then write the service results to the http response.
type CompilationAPIRouter interface { 
	CompilationsIdArtifactsGet(http.ResponseWriter, *http.Request)
	CompilationsIdCancelPost(http.ResponseWriter, *http.Request)
	CompilationsIdGet(http.ResponseWriter, *http.Request)
	CompilationsIdLogsGet(http.ResponseWriter, *http.Request)
	CompilationsPost(http.ResponseWriter, *http.Request)
}
// StatusAPIRouter defines the required methods for binding the api requests to a responses for the StatusAPI
// The StatusAPIRouter implementation should parse necessary information from the http request,
// pass the data to a StatusAPIServicer to perform the required actions, then write the service results to the http response.
type StatusAPIRouter interface { 
	AliveGet(http.ResponseWriter, *http.Request)
}


// CompilationAPIServicer defines the api actions for the CompilationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CompilationAPIServicer interface { 
	CompilationsIdArtifactsGet(context.Context, string, string) (ImplResponse, error)
	CompilationsIdCancelPost(context.Context, string) (ImplResponse, error)
	CompilationsIdGet(context.Context, string) (ImplResponse, error)
	CompilationsIdLogsGet(context.Context, string) (ImplResponse, error)
	CompilationsPost(context.Context, HandlerCompilation) (ImplResponse, error)
}


// StatusAPIServicer defines the api actions for the StatusAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type StatusAPIServicer interface { 
	AliveGet(context.Context) (ImplResponse, error)
}
