// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// CompilationAPIService is a service that implements the logic for the CompilationAPIServicer
// This service should implement the business logic for every endpoint for the CompilationAPI API.
// Include any external packages or services that will be required by this service.
type CompilationAPIService struct {
}

// NewCompilationAPIService creates a default api service
func NewCompilationAPIService() *CompilationAPIService {
	return &CompilationAPIService{}
}

// CompilationsIdArtifactsGet - Get the compilation arfitacts
func (s *CompilationAPIService) CompilationsIdArtifactsGet(ctx context.Context, id string, type_ string) (ImplResponse, error) {
	// TODO - update CompilationsIdArtifactsGet with the required logic for this service method.
	// Add api_compilation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, HandlerArtifactResponse{}) or use other options such as http.Ok ...
	// return Response(200, HandlerArtifactResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, HandlerErrBadRequestResponse{}) or use other options such as http.Ok ...
	// return Response(400, HandlerErrBadRequestResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, HandlerErrUnauthorizedResponse{}) or use other options such as http.Ok ...
	// return Response(401, HandlerErrUnauthorizedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, HandlerErrForbiddenResponse{}) or use other options such as http.Ok ...
	// return Response(403, HandlerErrForbiddenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, HandlerErrNotFoundResponse{}) or use other options such as http.Ok ...
	// return Response(404, HandlerErrNotFoundResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, HandlerErrMethodNotAllowedResponse{}) or use other options such as http.Ok ...
	// return Response(405, HandlerErrMethodNotAllowedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, HandlerErrGoneResponse{}) or use other options such as http.Ok ...
	// return Response(410, HandlerErrGoneResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, HandlerErrRateLimitExceededResponse{}) or use other options such as http.Ok ...
	// return Response(429, HandlerErrRateLimitExceededResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, HandlerErrInternalServerErrorResponse{}) or use other options such as http.Ok ...
	// return Response(500, HandlerErrInternalServerErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, HandlerErrServiceUnavailableResponse{}) or use other options such as http.Ok ...
	// return Response(503, HandlerErrServiceUnavailableResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CompilationsIdArtifactsGet method not implemented")
}

// CompilationsIdCancelPost - Stop a compilation
func (s *CompilationAPIService) CompilationsIdCancelPost(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update CompilationsIdCancelPost with the required logic for this service method.
	// Add api_compilation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, HandlerCompilationResponse{}) or use other options such as http.Ok ...
	// return Response(200, HandlerCompilationResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, HandlerErrBadRequestResponse{}) or use other options such as http.Ok ...
	// return Response(400, HandlerErrBadRequestResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, HandlerErrUnauthorizedResponse{}) or use other options such as http.Ok ...
	// return Response(401, HandlerErrUnauthorizedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, HandlerErrForbiddenResponse{}) or use other options such as http.Ok ...
	// return Response(403, HandlerErrForbiddenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, HandlerErrNotFoundResponse{}) or use other options such as http.Ok ...
	// return Response(404, HandlerErrNotFoundResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, HandlerErrMethodNotAllowedResponse{}) or use other options such as http.Ok ...
	// return Response(405, HandlerErrMethodNotAllowedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, HandlerErrGoneResponse{}) or use other options such as http.Ok ...
	// return Response(410, HandlerErrGoneResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, HandlerErrRateLimitExceededResponse{}) or use other options such as http.Ok ...
	// return Response(429, HandlerErrRateLimitExceededResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, HandlerErrInternalServerErrorResponse{}) or use other options such as http.Ok ...
	// return Response(500, HandlerErrInternalServerErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, HandlerErrServiceUnavailableResponse{}) or use other options such as http.Ok ...
	// return Response(503, HandlerErrServiceUnavailableResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CompilationsIdCancelPost method not implemented")
}

// CompilationsIdGet - Get the status of a compilation
func (s *CompilationAPIService) CompilationsIdGet(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update CompilationsIdGet with the required logic for this service method.
	// Add api_compilation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, HandlerCompilationResponse{}) or use other options such as http.Ok ...
	// return Response(200, HandlerCompilationResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, HandlerErrBadRequestResponse{}) or use other options such as http.Ok ...
	// return Response(400, HandlerErrBadRequestResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, HandlerErrUnauthorizedResponse{}) or use other options such as http.Ok ...
	// return Response(401, HandlerErrUnauthorizedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, HandlerErrForbiddenResponse{}) or use other options such as http.Ok ...
	// return Response(403, HandlerErrForbiddenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, HandlerErrNotFoundResponse{}) or use other options such as http.Ok ...
	// return Response(404, HandlerErrNotFoundResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, HandlerErrMethodNotAllowedResponse{}) or use other options such as http.Ok ...
	// return Response(405, HandlerErrMethodNotAllowedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, HandlerErrGoneResponse{}) or use other options such as http.Ok ...
	// return Response(410, HandlerErrGoneResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, HandlerErrRateLimitExceededResponse{}) or use other options such as http.Ok ...
	// return Response(429, HandlerErrRateLimitExceededResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, HandlerErrInternalServerErrorResponse{}) or use other options such as http.Ok ...
	// return Response(500, HandlerErrInternalServerErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, HandlerErrServiceUnavailableResponse{}) or use other options such as http.Ok ...
	// return Response(503, HandlerErrServiceUnavailableResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CompilationsIdGet method not implemented")
}

// CompilationsIdLogsGet - Get the compilation logs
func (s *CompilationAPIService) CompilationsIdLogsGet(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update CompilationsIdLogsGet with the required logic for this service method.
	// Add api_compilation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, HandlerLogsResponse{}) or use other options such as http.Ok ...
	// return Response(200, HandlerLogsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, HandlerErrBadRequestResponse{}) or use other options such as http.Ok ...
	// return Response(400, HandlerErrBadRequestResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, HandlerErrUnauthorizedResponse{}) or use other options such as http.Ok ...
	// return Response(401, HandlerErrUnauthorizedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, HandlerErrForbiddenResponse{}) or use other options such as http.Ok ...
	// return Response(403, HandlerErrForbiddenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, HandlerErrNotFoundResponse{}) or use other options such as http.Ok ...
	// return Response(404, HandlerErrNotFoundResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, HandlerErrMethodNotAllowedResponse{}) or use other options such as http.Ok ...
	// return Response(405, HandlerErrMethodNotAllowedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, HandlerErrGoneResponse{}) or use other options such as http.Ok ...
	// return Response(410, HandlerErrGoneResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, HandlerErrRateLimitExceededResponse{}) or use other options such as http.Ok ...
	// return Response(429, HandlerErrRateLimitExceededResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, HandlerErrInternalServerErrorResponse{}) or use other options such as http.Ok ...
	// return Response(500, HandlerErrInternalServerErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, HandlerErrServiceUnavailableResponse{}) or use other options such as http.Ok ...
	// return Response(503, HandlerErrServiceUnavailableResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CompilationsIdLogsGet method not implemented")
}

// CompilationsPost - Add a new compilation
func (s *CompilationAPIService) CompilationsPost(ctx context.Context, value HandlerCompilation) (ImplResponse, error) {
	// TODO - update CompilationsPost with the required logic for this service method.
	// Add api_compilation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, HandlerCompilationResponse{}) or use other options such as http.Ok ...
	// return Response(201, HandlerCompilationResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, HandlerErrBadRequestResponse{}) or use other options such as http.Ok ...
	// return Response(400, HandlerErrBadRequestResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, HandlerErrUnauthorizedResponse{}) or use other options such as http.Ok ...
	// return Response(401, HandlerErrUnauthorizedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, HandlerErrForbiddenResponse{}) or use other options such as http.Ok ...
	// return Response(403, HandlerErrForbiddenResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, HandlerErrMethodNotAllowedResponse{}) or use other options such as http.Ok ...
	// return Response(405, HandlerErrMethodNotAllowedResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, HandlerErrRateLimitExceededResponse{}) or use other options such as http.Ok ...
	// return Response(429, HandlerErrRateLimitExceededResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, HandlerErrInternalServerErrorResponse{}) or use other options such as http.Ok ...
	// return Response(500, HandlerErrInternalServerErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, HandlerErrServiceUnavailableResponse{}) or use other options such as http.Ok ...
	// return Response(503, HandlerErrServiceUnavailableResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CompilationsPost method not implemented")
}
