// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrNotFoundResponse - ErrNotFoundResponse represents a not found response
type HandlerErrNotFoundResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrNotFoundResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrNotFoundResponseRequired(obj HandlerErrNotFoundResponse) error {
	return nil
}

// AssertHandlerErrNotFoundResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrNotFoundResponseConstraints(obj HandlerErrNotFoundResponse) error {
	return nil
}
