// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerSketch - Sketch represents a sketch to be compiled
type HandlerSketch struct {

	Files []HandlerFile `json:"files,omitempty"`

	Ino HandlerFile `json:"ino,omitempty"`

	Metadata HandlerIncludedLibraries `json:"metadata,omitempty"`

	Name string `json:"name,omitempty"`
}

// AssertHandlerSketchRequired checks if the required fields are not zero-ed
func AssertHandlerSketchRequired(obj HandlerSketch) error {
	for _, el := range obj.Files {
		if err := AssertHandlerFileRequired(el); err != nil {
			return err
		}
	}
	if err := AssertHandlerFileRequired(obj.Ino); err != nil {
		return err
	}
	if err := AssertHandlerIncludedLibrariesRequired(obj.Metadata); err != nil {
		return err
	}
	return nil
}

// AssertHandlerSketchConstraints checks if the values respects the defined constraints
func AssertHandlerSketchConstraints(obj HandlerSketch) error {
	for _, el := range obj.Files {
		if err := AssertHandlerFileConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertHandlerFileConstraints(obj.Ino); err != nil {
		return err
	}
	if err := AssertHandlerIncludedLibrariesConstraints(obj.Metadata); err != nil {
		return err
	}
	return nil
}
