// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrUnauthorizedResponse - ErrUnauthorizedResponse represents an unauthorized response
type HandlerErrUnauthorizedResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrUnauthorizedResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrUnauthorizedResponseRequired(obj HandlerErrUnauthorizedResponse) error {
	return nil
}

// AssertHandlerErrUnauthorizedResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrUnauthorizedResponseConstraints(obj HandlerErrUnauthorizedResponse) error {
	return nil
}
