// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrRateLimitExceededResponse - ErrRateLimitExceededResponse represents a rate limit exceeded response
type HandlerErrRateLimitExceededResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrRateLimitExceededResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrRateLimitExceededResponseRequired(obj HandlerErrRateLimitExceededResponse) error {
	return nil
}

// AssertHandlerErrRateLimitExceededResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrRateLimitExceededResponseConstraints(obj HandlerErrRateLimitExceededResponse) error {
	return nil
}
