// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrInternalServerErrorResponse - ErrInternalServerErrorResponse represents an internal server error response
type HandlerErrInternalServerErrorResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrInternalServerErrorResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrInternalServerErrorResponseRequired(obj HandlerErrInternalServerErrorResponse) error {
	return nil
}

// AssertHandlerErrInternalServerErrorResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrInternalServerErrorResponseConstraints(obj HandlerErrInternalServerErrorResponse) error {
	return nil
}
