// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrBadRequestResponse - ErrBadRequestResponse represents a bad request response
type HandlerErrBadRequestResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrBadRequestResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrBadRequestResponseRequired(obj HandlerErrBadRequestResponse) error {
	return nil
}

// AssertHandlerErrBadRequestResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrBadRequestResponseConstraints(obj HandlerErrBadRequestResponse) error {
	return nil
}
