// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrGoneResponse - ErrGoneResponse represents a gone response
type HandlerErrGoneResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrGoneResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrGoneResponseRequired(obj HandlerErrGoneResponse) error {
	return nil
}

// AssertHandlerErrGoneResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrGoneResponseConstraints(obj HandlerErrGoneResponse) error {
	return nil
}
