// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrMethodNotAllowedResponse - ErrMethodNotAllowedResponse represents a method not allowed response
type HandlerErrMethodNotAllowedResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrMethodNotAllowedResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrMethodNotAllowedResponseRequired(obj HandlerErrMethodNotAllowedResponse) error {
	return nil
}

// AssertHandlerErrMethodNotAllowedResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrMethodNotAllowedResponseConstraints(obj HandlerErrMethodNotAllowedResponse) error {
	return nil
}
