// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerAliveResponse - AliveResponse represents a response for the alive endpoint
type HandlerAliveResponse struct {

	Message string `json:"message,omitempty"`
}

// AssertHandlerAliveResponseRequired checks if the required fields are not zero-ed
func AssertHandlerAliveResponseRequired(obj HandlerAliveResponse) error {
	return nil
}

// AssertHandlerAliveResponseConstraints checks if the values respects the defined constraints
func AssertHandlerAliveResponseConstraints(obj HandlerAliveResponse) error {
	return nil
}
