// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerCompilation - Compilation represents a compilation request
type HandlerCompilation struct {

	Fqbn string `json:"fqbn,omitempty"`

	Ota bool `json:"ota,omitempty"`

	// Path string `json:\"path\"`
	Sketch HandlerSketch `json:"sketch,omitempty"`

	Verbose bool `json:"verbose,omitempty"`
}

// AssertHandlerCompilationRequired checks if the required fields are not zero-ed
func AssertHandlerCompilationRequired(obj HandlerCompilation) error {
	if err := AssertHandlerSketchRequired(obj.Sketch); err != nil {
		return err
	}
	return nil
}

// AssertHandlerCompilationConstraints checks if the values respects the defined constraints
func AssertHandlerCompilationConstraints(obj HandlerCompilation) error {
	if err := AssertHandlerSketchConstraints(obj.Sketch); err != nil {
		return err
	}
	return nil
}
