// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrServiceUnavailableResponse - ErrServiceUnavailableResponse represents a service unavailable response
type HandlerErrServiceUnavailableResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrServiceUnavailableResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrServiceUnavailableResponseRequired(obj HandlerErrServiceUnavailableResponse) error {
	return nil
}

// AssertHandlerErrServiceUnavailableResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrServiceUnavailableResponseConstraints(obj HandlerErrServiceUnavailableResponse) error {
	return nil
}
