// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerCompilationResponse - CompilationResponse represents a response for a compilation request
type HandlerCompilationResponse struct {

	Id string `json:"id,omitempty"`

	Status string `json:"status,omitempty"`
}

// AssertHandlerCompilationResponseRequired checks if the required fields are not zero-ed
func AssertHandlerCompilationResponseRequired(obj HandlerCompilationResponse) error {
	return nil
}

// AssertHandlerCompilationResponseConstraints checks if the values respects the defined constraints
func AssertHandlerCompilationResponseConstraints(obj HandlerCompilationResponse) error {
	return nil
}
