// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerIncludedLibraries - IncludedLibraries represents the libraries to be included in the compilation
type HandlerIncludedLibraries struct {

	IncludedLibs []HandlerLibrary `json:"included_libs,omitempty"`
}

// AssertHandlerIncludedLibrariesRequired checks if the required fields are not zero-ed
func AssertHandlerIncludedLibrariesRequired(obj HandlerIncludedLibraries) error {
	for _, el := range obj.IncludedLibs {
		if err := AssertHandlerLibraryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertHandlerIncludedLibrariesConstraints checks if the values respects the defined constraints
func AssertHandlerIncludedLibrariesConstraints(obj HandlerIncludedLibraries) error {
	for _, el := range obj.IncludedLibs {
		if err := AssertHandlerLibraryConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
