// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerArtifactResponse - ArtifactResponse represents a response for a compilation artifacts request
type HandlerArtifactResponse struct {

	Bin string `json:"bin,omitempty"`

	Elf string `json:"elf,omitempty"`

	Hex string `json:"hex,omitempty"`

	Name string `json:"name,omitempty"`
}

// AssertHandlerArtifactResponseRequired checks if the required fields are not zero-ed
func AssertHandlerArtifactResponseRequired(obj HandlerArtifactResponse) error {
	return nil
}

// AssertHandlerArtifactResponseConstraints checks if the values respects the defined constraints
func AssertHandlerArtifactResponseConstraints(obj HandlerArtifactResponse) error {
	return nil
}
