// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Builder API Documentation
 *
 * This is the documentation for the Builder API service.
 *
 * API version: 2.0
 * Contact: support@swagger.io
 */

package openapi




// HandlerErrForbiddenResponse - ErrForbiddenResponse represents a forbidden response
type HandlerErrForbiddenResponse struct {

	Err string `json:"err,omitempty"`
}

// AssertHandlerErrForbiddenResponseRequired checks if the required fields are not zero-ed
func AssertHandlerErrForbiddenResponseRequired(obj HandlerErrForbiddenResponse) error {
	return nil
}

// AssertHandlerErrForbiddenResponseConstraints checks if the values respects the defined constraints
func AssertHandlerErrForbiddenResponseConstraints(obj HandlerErrForbiddenResponse) error {
	return nil
}
